### PR TITLE
docs: mention peerDependencies install

### PR DESCRIPTION
**Pull request by escapedcat**
make it easier for beginners to setup this module

### CODE REVIEW

**Comment by F-loat** [comment]
Thanks. Is  it better to revert 59671094d919258e4c602f56d889b8094d5fa97c ?

**Comment by escapedcat** [comment]
Ah, cool. I think that would be helpful, yes.

**Comment by F-loat** [comment]
Done.

**Comment by escapedcat** [comment]
谢谢啊

**Pull request closed without merging**
